<a href="https://colab.research.google.com/github/sejal-oli7/python/blob/main/python%20/%20%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas Exercise 1
We need pandas to get to know about the pandas.

In [1]:
#@ Importing necessary
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

df = pd.read_csv("food.tsv", sep="\t")

print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'food.tsv'

## Pandas EXercise 2

In [ ]:
#@ IMporting Library
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"

df = pd.read_csv(
    url,
    sep="|",
    index_col="user_id"
)

print(df.head())

In [ ]:
df.head(25)

In [ ]:
df.tail(10)

In [ ]:
#@ how many numbers of data we have?
df.shape [0]

In [ ]:
df.columns

In [ ]:

df.dtypes

In [ ]:
#@ only print occupation columns
df.occupation

In [ ]:
df['occupation']

In [ ]:
#@ how many different occupations are in the datasets
df.occupation.nunique()

In [ ]:
df.occupation.value_counts()

In [ ]:
df.occupation.value_counts().count()

In [ ]:
#@ Lets describe your dataset by summarizing it
df.describe()

Only numeric columns are return , if you only describe the dataframe

In [ ]:
#@ If we need all then
df.describe(include="all")

In [ ]:
df.occupation.describe()

In [ ]:
#@ what is the mean age of users?
round(df.age.mean())

In [ ]:
#@ the least occurance of age
df.age.value_counts().tail()

## Pandas Exercise3

In [ ]:
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
df = pd.read_csv(url, sep='\t')

In [4]:

#@ inspecting the dataset
df.head(20)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75

In [5]:
#@ number of observation
df.shape[0]

4622

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [7]:
df.shape[1]

5

In [8]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [9]:
#@ which was the most order items
#group by
i = df.groupby('item_name')
i
i= i.sum()
i = i.sort_values(['quantity'], ascending=False)
i.head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...

In [10]:


#@ what was the most order item in the choice description column
df.groupby('choice_description').sum().sort_values(['quantity'], ascending=False).head(1)

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,$2.18 $1.09 $1.09 $6.49 $2.18 $1.25 $1.09 $6.4...

In [11]:
import pandas as pd
data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "class": ["V", "V", "VI", "VI", "V", "VI"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ],
    "date_Of_Birth": [
        "15/05/2002",
        "17/05/2002",
        "16/02/1999",
        "25/09/1998",
        "11/05/2002",
        "15/09/1997"
    ],
    "age": [12, 12, 13, 13, 14, 12],
    "height": [173, 192, 186, 167, 151, None],
    "weight": [35, 32, 33, 30, 31, None],
    "address": [
        "street1",
        "street2",
        "street3",
        "street1",
        "street2",
        None
    ]
}

df = pd.DataFrame(data)

# Group by school
grouped = df.groupby("school")

# Check the type
print(type(grouped))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [12]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "age": [12, 12, 13, 13, 14, 12]
}

df = pd.DataFrame(data)

result = df.groupby("school")["age"].agg(
    ["mean", "min", "max"]
)

print(result)

        mean  min  max
school
s001    12.5   12   13
s002    13.0   12   14
s003    13.0   13   13
s004    12.0   12   12

In [13]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "class": ["V", "V", "VI", "VI", "V", "VI"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ],
    "age": [12, 12, 13, 13, 14, 12]
}

df = pd.DataFrame(data)

grouped = df.groupby(["school", "class"])

for name, group in grouped:
    print("Group:", name)
    print(group)
    print()

Group: ('s001', 'V')
  school class            name  age
0   s001     V  Alberto Franco   12

Group: ('s001', 'VI')
  school class          name  age
3   s001    VI  Eesha Hinton   13

Group: ('s002', 'V')
  school class          name  age
1   s002     V  Gino Mcneill   12
4   s002     V  Gino Mcneill   14

Group: ('s003', 'VI')
  school class         name  age
2   s003    VI  Ryan Parkes   13

Group: ('s004', 'VI')
  school class          name  age
5   s004    VI  David Parkes   12

In [14]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ]
}

df = pd.DataFrame(data)

grouped = df.groupby("school")

groups = list(grouped)

print(groups)

[('s001',   school            name
0   s001  Alberto Franco
3   s001    Eesha Hinton), ('s002',   school          name
1   s002  Gino Mcneill
4   s002  Gino Mcneill), ('s003',   school         name
2   s003  Ryan Parkes), ('s004',   school          name
5   s004  David Parkes)]

In [15]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "class": ["V", "V", "VI", "VI", "V", "VI"]
}

df = pd.DataFrame(data)

result = df.groupby("school").size()

print(result)

school
s001    2
s002    2
s003    1
s004    1
dtype: int64

In [20]:
import pandas as pd

df = pd.read_csv("dataset.csv")

df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   school  6 non-null      object
 1   class   6 non-null      object
dtypes: object(2)
memory usage: 228.0+ bytes

In [18]:
df.columns

Index(['school', 'class'], dtype='object')