<a href="https://colab.research.google.com/github/sejal-oli7/python/blob/main/python%20/%20regression_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Intro to Machine Learning
**Machine Learning has two categories:**
- classification: Its simply categorizing an unknown variable to a known state. That means, we will have a dataset along with categories as a training examples. Now our task would be, to classify any variable to one of the predefined categories, then we call it as a classification problem. Eg. cat vs dog classification, disease classfication problem, face recognition system, vehicle number plate detection and classifier etc

- regression: Its simply a prediction. When we have a numbers of data in a columns or strucutured data, and we need to predict based upon hisotorical dataset, then we call it as regression problem. E.g house prices prediction,
stock marget prediction. That means anything related with prediction, we call it as regression problem

**Our task:**

A user wants to sell a car on an online classified website, and the site asks them to enter a price. If they dont know much the car is worth, they just need to guess. To those people or company, we want to help: How? the user describes the car, and our Machine learning model suggest the best prices.

**Question:** Which type of problem is this? Regression or Classification?

car:
- model
- km running
- condition
- numbers of hands
- resale
- parts avaialbity

To start any machine learning Model, here are the checklist:
-  dataset (https://www.kaggle.com/datasets/CooperUnion/cardataset)

for this project, lets collect the data from kaggle

## Implementation Guidelines?
**Our plan:**
To start this project, we will follow several steps:
- Get the data and do exploratory data analysis: Just look at the data and try learn more about data

- Prepare the dataset into train for linear regression model to predict price of the car

- Go into the details of how linear regression is implemented,

- Once you build the model, you need to evaluate the quality of your model with LR: RMSE. RMSE stands for root mean square error, a metric for evaluating quality of model prediction

- Do some feature engineering: The process of creating a new features, new characterisitcs that we can use for our model

- Deal with numerical stability problems and see how to solve them with regularization

- Finally, use that model

## Data Preparation

You need to work with data

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/data.csv')
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [ ]:
df.tail(10)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
11904,BMW,Z8,2002,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,130000
11905,BMW,Z8,2003,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,131500
11906,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46020
11907,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56570
11908,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50520
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [ ]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

Problems identified
- looking at columns, there is some inconsistency, i.e sometime there are uppercase letter (Make, Model), sometimes,,there are spaces (Engine Fuel Type), sometime underscore (_)

Our tasks:
1.
- lets make it uniform converting all columns header into lowercase,
e.g Model -> model
- also replace space with _  i.e Driven_Wheels -> driven_wheels , Engine HP -> engine_hp

2.
Finding out string columns
- we need to find out which columns are string, we cannot apply string method to numbers. For that we use dtypes attributes. It tells us, for every column, what type of data it is

3. Normalize the data as well, means lowercase the values and replace spaces with underscore

## Exploratory Data Analysis

we look for every column, see what kind of values are there, and try to get a feeling for the data and the problem before we create a model

- In this steps, your main agenda should be to learn more and more about data
- we already know, some columns are strings and some are numbers, To see what is inside each of them, we iterete over all the columns,and print some stat for every one, the column name, a few values, and the numbers of unique values.
- Distribution of prices: we need to figure out the distribution of prices,.

for visualizing we need to implement matplotlib.
- for this, we can visualize, the price against

- Also check for null counts, if any for all the columns